### PR TITLE
Support inline editing for authors and affiliations 

### PR DESCRIPTION
**Pull request by NateWr**
Here's a start on some work for authors and affiliations. It allows them to be edited inline and opens the associated panel on the right when doing so.

Further considerations:
- It'd be nice to link authors to their affiliations. I think usually reference numbers like `Jane Doe<sup>1</sup> <sup>2</sup>` are used for this.
- The `,` and `;` separators should be translatable.
- Since `,` and `;` are used as separators, should we prevent their use within these fields? If so, would that entail an extended `TextPropertyEditor` with some event listeners or is there already some facility for listening to events on a `TextPropertyEditor`?

### CODE REVIEW

**Comment by michael** [comment]
Thanks for the suggestion! I've had inline editing of authors and affiliations available in earlier versions. However, given that we want to move towards structured elements (separate given-names and surname) or have more complex affiliation records we thought of moving this into the metadata section and only render a preview. 

Regarding associating authors and affiliations, that's only a rendering issue. the data we have covered already. So we could render them in the AuthorsList and AffiliationsList, but without creating explicit labels in the XML source.

I'll leave this PR open for further discussion. Needs a bit more thinking from our side.

**Comment by NateWr** [comment]
That makes sense. Should I work on given names and surnames, and linking affiliations to authors in the preview? I think that shouldn't be too difficult.

**Comment by michael** [comment]
Hey! Would be much appreciated!  We should do a specification round before we start though. I'll write up a separate issue.

**Comment by michael** [comment]
This is now done through entity editor. Closing.

**Pull request closed without merging**
