### PR TITLE
App initialization logic rewritten

### PR DESCRIPTION
**Pull request by meinbrodt**
Hi Everybody, 

the whole rewrite tries to achieve the following things: 

- Enforce better separation of concerns. For instance, the `texture/src/article/ArticleLoader.js` class loads the article document but creates also the texture editor session. This two steps have been separated into two service classes: (1) `texture/src/sessions/EditorSessionsGenerator.js` and (2) `texture/src/dar/DocumentLoader.js`. Furthermore, I "moved" a lot of functions from the `PersistedDocumentArchive` and `TextureArchive` class to dedicated external service classes.

- A cleaner and more easy to use approach (in my opinion) to configure an application or better it's contained parts (dar and dar-clients) using dedicated configuration classes instead of using getter methods on the app classes.

- A separation of the those parts of the code necessary for "read-only apps" and "read-write editor apps". The central change here is the replacement of the `texture/src/dar/PersistedDocumentArchive.js` class with two new classes: 
(1) `texture/src/dar/DocumentArchiveReadOnly.js` (contains only those methods necessary for displaying a dar) 
(2) `texture/src/dar/DocumentArchiveReadWrite.js` (inherits all methods from the read-only class and furthermore contains all the necessary methods for editing and saving a dar). 
However, also several configuration and service classes follow that logic (e.g. see the `texture/src/dar/DocumentArchiveReadWriteExporter.js` and `texture/src/dar/DocumentArchiveReadOnlyExporter.js`)

- Achieve a better understandability of the code via promises and promises chaining. A good example are the load methods of the `DocumentArchiveReadOnly` and `DocumentArchiveReadWrite` classes.

I know there are a lot of changes and I don't expect that all or any of them to be accepted, however I hope that this can start a conversation on how to further improve the code.

Last but not least, I just wanted to say that I really like the project and hope to use it for some of our projects. If you need any help with something just let me know. 

Regards, Matthias

### CODE REVIEW

**Comment by oliver----** [comment]
Hello @meinbrodt,

Thank you for this huge contribution.

We are currently refactoring Texture internally, however, your changes look pretty complementary.
We need to investigate how we can get your work merged into our latest dev (branch `metadata-editor`).

Cheers,
Oliver

**Comment by oliver----** [comment]
Maybe we could setup a call to talk about this in more detail?

**Comment by meinbrodt** [comment]
> Maybe we could setup a call to talk about this in more detail?

@oliver I'm not sure if this is directed at me. If yes, I'm in. ;)

**Comment by michael** [comment]
@meinbrodt yes it is directed at you. ;) Where are you based? Maybe we could talk tomorrow (Thursday) afternoon.

**Comment by michael** [comment]
(we are in CEST)

**Comment by meinbrodt** [comment]
@michael and @oliver tomorrow or friday would work for me after 5 pm (CEST).

**Comment by michael** [comment]
Tomorrow 5pm sounds good. Can you create a Google hangout? And invite michael / oliver  [at] substance.io

See you :)

**Comment by meinbrodt** [comment]
@michael Done - I hope. I created a new conversation (Unterhaltung) and added you both. See you tomorrow.

**Comment by michael** [comment]
Hey, we can't see your conversation/invitation. We are here currently: https://meet.google.com/tbr-iric-unh

Can you join this channel?

**Comment by oliver----** [comment]
Closing this because it is out-dated. We will rework the app initialisation soon.

**Pull request closed without merging**
