### PR TITLE
Import bibliography.

### PR DESCRIPTION
**Pull request by Integral**
Why: We want to give an ability to import ref by providing DOI list and fetching data.
What: This PR adds an ability to enter list of DOIs and fetch data via DataCite.

### CODE REVIEW

**Comment by Integral** [comment]
@michael couple of thoughts: we should check no connection case and fetch data from doi.org (for that we need special util, so we can do it with custom headers).

**Comment by michael** [comment]
@Integral took a quick look. 

Few bugs:

- authors and editors are not extracted currently
- split DOIs by space (`" "`) not by `","`

Missing:

- error handling and reporting
  - convertCSLJSON should throw an error for unsupported types (and try catch outside)
  - errors (like loading errors or conversion errors) should be indicated and displayed
- loading indicator (and blocking ui while loading)

UI with loading and error states could look like this:

image

**Comment by michael** [comment]
Will do a quick round of code cleanup, expect some commits in next 30minutes.

**Comment by Integral** [comment]
Let's decide what exactly do we need until merge and improve other things
afterwards

**Comment by michael** [comment]
Yep. When there are some invalid DOI's, we should not update the search string. Just leave everything as is. The user then can fix it manually (e.g. when they made just a typo).

**Comment by michael** [comment]
Need a bit more time. Will write to you in Slack soon.

**Comment by Integral** [comment]
@michael I think we should merge now. Then Philipp could work on other converters and I will work more on:
- no connection errors
- doi.org parsing
- import CSL JSON via DND

**Comment by michael** [comment]
Thank you @Integral! I will check and merge asap.

**Pull request merged**
