### PR TITLE
Ui improvements

### PR DESCRIPTION
**Pull request by Integral**
As suggested in #1189.

### CODE REVIEW

**Comment by oliver----** [comment]
This was more massive than we thought this morning.

**Comment by oliver----** [comment]
But I am very proud of it now :)

**Comment by oliver----** [comment]
@Integral how do you like this colour? ;)

**Comment by oliver----** [comment]
@Integral everything seems to be working. Now we need to fix styles. And also still left is hiding inactive groups from the 'Edit' dropdown.

**Comment by Integral** [comment]
👍

**Comment by Integral** [comment]
I would say it is now in a good shape, but want to discuss one tiny detail.

**Pull request merged**
