### PR TITLE
Dedicated editor for translations.

### PR DESCRIPTION
**Pull request by michael**
@oliver---- can you check if this is going into an ok direction?

@Integral there's more to do here and I could need your help, but just finish other task first.

### CODE REVIEW

**Comment by oliver----** [comment]
@michael hard to say atm. I guess the challenge here is to find a Model for translations, that can be implemented well on top of JATS, but is general enough. I'd say, go ahead with your approach, and then let's see ;).
Maybe, at some point you could capture a version of a model for translations, without having the JATS based impl already in mind. (Or is it that already?)

**Comment by michael** [comment]
that's what I'm trying to acchieve with that Translatable API. I just define translatables, which have an id. E.g. `article-title` or `abstract` and then we can modify the original language as well as adding and updateing translations.

E.g. `model.addTranslation('es')`

`model.getTranslations()` will yield translation models.

**Comment by oliver----** [comment]
Sounds good. This sounds a bit like a mixin.. But for now we will only have titles and abstracts...

**Comment by michael** [comment]
We could also use it for figures then it gets a bit more of a dynamic nature, that's why I'm using ids for the translatables. E.g. each figure could produce a virtual view on the caption translatable.

`api.getTranslatable('fig1-caption-trans')`

The idea would be that we have all translations in one place (task-based for the translator person). So I would maybe not show them in the Figures section.  (if that's what we want)

**Comment by oliver----** [comment]
Yep. That is something we need to discuss with Editors.
- Dedicated Translations section
- Adding to cards in other collections (e.g. Figures)
- Or both

**Comment by michael** [comment]
Let's do a first shot, and present it to them. For the metadata editor demo i will leave it for title + abstract for now.

**Pull request merged**
