### PR TITLE
Entity Importers

### PR DESCRIPTION
**Pull request by michael**

### CODE REVIEW

**Comment by michael** [comment]
@oliver---- I worked on entity importer/exporters, as we discussed. Maybe you could have a look to check if on the right track. I'll be in Amsterdam for next few days and will return on Tuesday.

Code is not functional yet, just a sketch.

**Comment by michael** [comment]
Code is now functional, and supports journal and book citations. Remaining pub types must be added and tested.

**Comment by michael** [comment]
@Integral can you have a look at the code and give me feedback? You could take over the task of implementing the remaining pub types if you want to.

**Comment by Integral** [comment]
@michael, are you sure that PatentNumber and PatentCountry are not an array [here](https://github.com/substance/texture/blob/master/src/entities/EntityDatabase.js#L78)? E.g. are you sure that i can't use few `patent` elements inside patent publication type reference?

**Comment by michael** [comment]
We need to check with the publishers. But I think it would be good to have them as single properties, otherwise the UI gets complicated (create, delete buttons etc.). I will review your PR today and get this stuff merged.

**Pull request merged**
