### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/substance/texture/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/substance/texture).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by oliver----** [comment]
Hey!

Thanks. I am definitely interested. We run `standard` as a linter, but from a first glance your measure seem to reveal some more and also real issues.

**Comment by xcorail** [comment]
Hi @oliver---- 
I've seen that you enabled / disabled the automated code review
I am curious to know if you encountered any problem, or didn't like it, or ... 

Thanks

**Comment by oliver----** [comment]
Hey @xcorail,

I tried it and basically like it. 
Having a pretty light-weight CI setup we have very fast responses on a PR, and the LGTM response was too slow for my taste. Having only very few issues, I decided that a daily update is fine for me for now.

**Comment by xcorail** [comment]
Hey @oliver---- 
Thanks a lot for the feedback. 

Optimising the analysis is one of the high priority features on our roadmap right now, so I suggest that you keep an eye on our [forum](https://discuss.lgtm.com/) for news about this. 

Still curious: what would be an acceptable response time for your taste? I'd like to give this information to my product team.

Cheers

**Comment by oliver----** [comment]
I guess on our side we are a bit spoiled here ;)
The CI runs about 2 mins. Of course it would be nice to have a similar response with LGTM.
I guess something < 5 mins would be acceptable for us.

**Comment by sjvs** [comment]
Hi @oliver---- 

My colleague @xcorail asked me to chip in. Indeed, we're expecting a big performance improvement to land in the next 1-2 months. I had a quick look at the logs for #1050 (the only PR that was analysed by LGTM): there were about 7 minutes between LGTM receiving the webhook about #1050 and the status being posted. We're expecting that time to come down to well below 5 minutes.

I would like to note that LGTM is really not comparable to a linter / style checker, though. For example, we track the flow of data through applications to find injection vulnerabilities with very high precision: https://github.com/ampproject/amphtml/pull/13060. Such analyses do take a bit of time, and then give you cool results in return :slightly_smiling_face:!

**Comment by oliver----** [comment]
Hey,

I assumed that you were doing more sophisticated code analysis, and also absolutely understand that this needs a bit longer.
Let's see how your performance improvements turn out. Beyond that, I am also totally fine with an analysis on a daily basis.

**Pull request merged**
