### PR TITLE
Preformat

### PR DESCRIPTION
**Pull request by Integral**
## Why

As requested in #966 we want to support preformat blocks.

## What

This PR contains necessarily schema changes for using `preformat` tag as well as converters, styles and command. It also removes any ability to use `code` tag since we are not allowing usage of few tags per use case.

### CODE REVIEW

**Comment by oliver----** [comment]
This is looking good.

@Integral Should we do something about the anomality of `parseSnippet` in presence of CDATA, i.e. do you think this is inconsistent?

**Comment by Integral** [comment]
@oliver---- good question
It's not very consistent indeed.
I think that we should do some iteration on CDATA, there is a bug there, which I described here: https://github.com/substance/substance/issues/1233, it's getting important with block formulas.
Generally speaking I think that as an API user I would expect to get CDATA content in the same way as regular textual data, without any additional calls. If it's possible.

**Comment by oliver----** [comment]
I'll try this out and then merge.

**Comment by oliver----** [comment]
> It's not very consistent indeed.
> I think that we should do some iteration on CDATA, there is a bug there, which I described here: [substance/substance#1233](https://github.com/substance/substance/issues/1233), it's getting important with block formulas.
> Generally speaking I think that as an API user I would expect to get CDATA content in the same way as regular textual data, without any additional calls. If it's possible.

I will track this in Substance

**Comment by Integral** [comment]
Thank you!

**Comment by oliver----** [comment]
https://github.com/substance/substance/issues/1234

**Comment by oliver----** [comment]
rebased.

**Pull request merged**
