### PR TITLE
Standardize references according to AMA style

### PR DESCRIPTION
**Pull request by zuphilip**
This solves #430.

### CODE REVIEW

**Comment by zuphilip** [comment]
The output looks like this:

texture-references

BTW is the schema for the bibliographic data fixed? I have the feeling, that one should change some things there...

**Comment by michael** [comment]
Hey, it's looking great. :) Will take a closer look tomorrow.

What should be fixed regarding the bibliographic data? (yes there may be issues)

**Comment by zuphilip** [comment]
I can open a new issue for the bibliographic schema, but will be busy the next days.

**Comment by michael** [comment]
Take your time. Thanks a lot for your help! :)

Will get this merged asap.

**Pull request merged**
