### PR TITLE
Metadata shortcuts

### PR DESCRIPTION
**Pull request by Integral**
Keyboard shortcuts for adding new entities via metadata panel.

### CODE REVIEW

**Comment by oliver----** [comment]
@Integral Which state is this in? I agree with your opinion, that we should rather fix the event handling problem than avoiding certain combos.

**Comment by Integral** [comment]
@oliver---- [here](https://github.com/substance/texture/issues/672#issuecomment-417360274) I reported the current state

**Comment by oliver----** [comment]
Ok. I have read this. Your comment indicates that this PR would be obsolete if we solved the 'global' key handling problem. Is that true?

**Comment by Integral** [comment]
@oliver----, I think we should reassign shortcuts in case of solving global problem. Let's maybe continue here?

**Comment by oliver----** [comment]
Yeah, I think it does not help us if we do this work 10 times. Let's first prepare the work by dealing with the global event problem.

**Pull request merged**
