### PR TITLE
First Iteration on Tables

### PR DESCRIPTION
**Pull request by oliver----**
# Why?

Tables have not been implemented sufficiently.

# What?

This PR introduces a Table implementation based on a very semantic internal model.
Feature-wise this is pretty complete:
- basic interaction
- header cells
- copy'n'paste
- merge/unmerge
- insert rows/cols

### CODE REVIEW

**Comment by oliver----** [comment]
texture-table

**Comment by oliver----** [comment]
Deleting a row leads to a bug

**Comment by michael** [comment]
Looks nice with the table selection interaction!

**Comment by oliver----** [comment]
Will add some tests before this PR is ready.

**Comment by michael** [comment]
Works nicely. It's a really minimal solution!

Few suggestions:

- right clicking should first select the cell and then bring up the context menu (currently the selection stays in the previously selected cell)
- if add a column/row we should probably try to replicate the style (e.g. make the first cell of a column a header if the previous one was a header too); potentially also continue with letters / numbers if we can detect that
- Would like to try opening up all the isolated nodes (figures, tables, disp-quote) and adding a handle (e.g. top-left) to select the full node.

**Comment by michael** [comment]
Should we get this merged and make a Texture Preview 2 release? We could trigger the consortium members for testing the new features (lists and tables).

**Comment by oliver----** [comment]
@michael this 'UI' testing is pretty cool :)

**Comment by oliver----** [comment]
I think we are good for now, and can merge.
I have established a foundation for testing the UI. This needs to be completed at some point, but good enough for now.

**Comment by oliver----** [comment]
@michael 
Your first suggestion was just a bug, which should be fixed now.
The second is on my list.
The last needs some collab...

**Comment by michael** [comment]
Yay! Of course I'm in for the UI improvements. But this is already pretty good, so not blocking a release I would say! :)

**Pull request merged**
