### PR TITLE
Author and reference editing from manuscript

### PR DESCRIPTION
**Pull request by Integral**
As suggested in #1187 we want to make authors and references selectable and expose contextual tool.
Agenda:
- [x] Introduce author selection
- [x] Introduce reference selection
- [x] Edit author contextual tool
- [x] Edit reference contextual tool

### CODE REVIEW

**Comment by Integral** [comment]
@oliver---- do we want to add more contextual tools now? E.g. create/remove and maybe moving?

**Comment by Integral** [comment]
Almost there with edit commands, but once again have a problem with view switching and scrolling.

**Comment by Integral** [comment]
Ok, looks like we need some other concept for switching view and scroll to. 
There is now `context.articlePanel.refs.content.send('executeCommand', this.name, params)` hack, which is working in case of "always active" commands like entity insertion. But this will not work for contextual tools since command will be disabled in metadata mode and not get executed.
We need to come up with some different idea.

**Comment by Integral** [comment]
Ok, for now we can switch view and scroll to, but without setting a selection.

**Comment by oliver----** [comment]
> @oliver---- do we want to add more contextual tools now? E.g. create/remove and maybe moving?

@Integral let's wait with that for now.

**Comment by oliver----** [comment]
Sweet. Thx!

**Pull request merged**
