### PR TITLE
Dev: move entity renderers to models

### PR DESCRIPTION
**Pull request by Integral**
## Why

See #1173.

## What

Entity renderers for all models except references are moved to member functions.

### CODE REVIEW

**Comment by oliver----** [comment]
@Integral we need to find out why this change is decreasing the test coverage.

**Comment by oliver----** [comment]
It seems that the toString() methods are never used.
@Integral do you have a suggestion? or should we just remove the toString() and add them when we need them?

**Comment by oliver----** [comment]
Strange. It must be something more. There are like +84 more missed lines now. I don't see how the toString() would be responsible for this.

**Comment by oliver----** [comment]
@Integral It seems that I have looked at the wrong report. Now it is only +4 misses which maps to the toString() usage. Still, if we are not using them, we should remove them.

**Comment by oliver----** [comment]
Commented out unused toString()
let's bring them in, when we need them.

**Comment by Integral** [comment]
@oliver---- There is a case where we might need something like that, for instance in multi select input, e.g. dropdown with affiliations (see #1266). If it's the only one place where we do this I think for now it's better to do it right in component to keep consistency in methods across entity models.

**Comment by oliver----** [comment]
Just don't want to have dead code from the get go. In case of `Organistation` we are using it already.

**Comment by oliver----** [comment]
An alternative could be to introduce a mixin or super class (RenderableNode) and have the default toString method there.

**Comment by Integral** [comment]
Yes! But let's wait with mixin until we'll sure about that

**Comment by oliver----** [comment]
Then we leave it as is. I.e. without dead code.

**Comment by Integral** [comment]
Absolute! No dead code!

**Pull request merged**
