### PR TITLE
Rewrite app init code after qc

### PR DESCRIPTION
**Pull request by oliver----**
Taking over PR #604 for discussions.

### CODE REVIEW

**Comment by oliver----** [comment]
Hey @meinbrodt 
Using this PR to discuss your original PR #604 and moving further.

There is a bit of a concept drift currently going on. I.e. we are considering a DAR agnostic of specific resource types. That means, our article should just be one option. This we want to address by having a configurator with nested configurations for the specific resource type.
We consider Texture now an editor with tabs for multiple resources.
Along with the article you could have a csv file in the DAR that is edited via a Spreadsheet interface.
So our original approach having an 'Substance.EditorSession' for each resource is obsolete.

**Comment by oliver----** [comment]
@meinbrodt have sent you an invite for collab

**Comment by meinbrodt** [comment]
> ... we are considering a DAR agnostic of specific resource types. That means, our article should just be one option. 

Great idea! I suppose the correct load, transformation and import routines (e.g. which importer, resource configurator etc. to use) would then be kicked off based upon in information about the resource contained in the manifest.xml file of the DAR right?

I think - correct me I'm wrong - this idea is already reflected rudimentarily in my implementation of the dar/DocumentLoader (see here: https://github.com/substance/texture/blob/rewrite-app-init-code-after-qc/src/dar/DocumentLoader.js) 

> We consider Texture now an editor with tabs for multiple resources.

Does that mean, that it won't be possible anymore to create a reader app without editing capabilities?

> So our original approach having a 'Substance.EditorSession' for each resource is obsolete.

This I don't fully understand, however, I still need to grasp the concept of a session. I haven't advanced this far yet.

**Comment by oliver----** [comment]
>> We consider Texture now an editor with tabs for multiple resources.
> Does that mean, that it won't be possible anymore to create a reader app without editing capabilities?

At least in the default configuration when run as app. A read-only version will be added, too, once as a preview in the editor (which could be used as a standalone reader, too) and as a command-line site-generator.

**Comment by oliver----** [comment]
>> So our original approach having a 'Substance.EditorSession' for each resource is obsolete.

> This I don't fully understand, however, I still need to grasp the concept of a session. I haven't advanced this far yet.

This just makes the DAR loading a bit simpler.

**Comment by oliver----** [comment]
Closing this, because it is outdated. We will rework the whole App initialisation code soon.

**Pull request closed without merging**
